title: Just Test
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://eehjunggnujhee.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


title: Just Test
description: Just Test
theme: just-the-docs

url: https://eehjunggnujhee.github.io/just-test

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/eehjunggnujhee/just-test
